---
title: "Books"
---

## Financing Firm Growth: The Role of Capital Markets in Low- and Middle-Income Countries

::: {.justified}

Financing Firm Growth: The Role of Capital Markets in Low- and Middle-Income Countries shows that the gap in capital market financing between low- and middle-income countries and high-income countries has narrowed, with resulting benefits for both the firms accessing those markets and for the countries in which they operate. The analysis reveals greater participation by firms from low- and middle-income countries in capital markets since the 2000s. Most of these firms are new participants in capital markets, and they tend to be smaller, younger, and more productive than those already participating. Firms are deploying capital raised in markets to become more productive—investing in physical assets, hiring more workers, and expanding operations, spurring growth both at the firm level and within their economies. To reach these findings, the analysis used a novel database of the universe of bond and equity issuances from companies between 1990 and 2022. The insights leverage data from nearly 80,000 firms worldwide, focusing on how 20,000 firms across 106 low- and middle-income countries access and use capital market financing.

:::

### Chapter 2. Expansion of Capital Markets Globally

[Download chapter](../files/books/Financing_Firm_Growth_Chapter_2.pdf){target="_blank"}

::: {.justified}

Hernando-Kaminsky, Pablo. 2025. “Expansion of Capital Markets Globally.” In Financing Firm Growth: The Role of Capital Markets in Low- and Middle-Income Countries, edited by Cesaire Meh and Sergio Schmukler, 11–28. Washington, DC: World Bank.

:::

### Chapter 3. Expansion of Capital Markets across Firms

[Download chapter](../files/books/Financing_Firm_Growth_Chapter_3.pdf){target="_blank"}
    
::: {.justified}

Hernando-Kaminsky, Pablo. 2025. “Expansion of Capital Markets across Firms.” In Financing Firm Growth: The Role of Capital Markets in Low- and Middle-Income Countries, edited by Cesaire Meh and Sergio Schmukler, 29–46. Washington, DC: World Bank.
:::